server:
  port: 8081
  servlet:
    context-path: /sample-idp

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.saml: TRACE
    org.opensaml.xmlsec: TRACE

spring:
  thymeleaf:
    cache: false
  security:
    saml2:
      network:
        read-timeout: 8000
        connect-timeout: 4000
      identity-provider:
        entity-id: blog.yl-online.top
        alias: saml-idp
        sign-metadata: true
        #sign-assertions: true
        #key-encryption-algorithm: rsa_1_5
        #encrypt-assertions: false
        #data-encryption-algorithm: aes256_cbc
        want-requests-signed: true
        default-signing-algorithm: rsa_sha256
        default-digest: sha256
        single-logout-enabled: true
        name-ids:
          - urn:oasis:names:tc:SAML:2.0:nameid-format:persistent
          - urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
          - urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified
        keys:
          active:
            name: active-idp-key
            private-key: |
              -----BEGIN RSA PRIVATE KEY-----
              MIIEowIBAAKCAQEAs0HxljgBLKtCGTUoCX/FyjzBNqB3aGr4m/01lafMHCfoXXeM
              x7MHnhWq7Vjgs3S/t8Ul+0DgI+O86ppvmLXHb8dDggTjoscFh/IycgIN/rEWnu++
              Q/Uh4JA+zX9so7vpY5NLCbGDMU0qFmVXwlTNY7hwNGnIBofMtZf1/1pKN8ingJqe
              zHWNLxiI/yYvzQiLxxM3YUR6147o6WmhJf4fMDtBv9f1YUG8SwWuAAzjFLbtcqFJ
              y2WGUQMzVl8TPp9MR+52d4G2aHcUvYslNIisR4uG41m4Avg8TITGoH1H7wvstktX
              4KPmI2/vSuEQJquOpnLGU8yng9aiZ4oUfcHUrQIDAQABAoIBADheBBm4gqYJND+4
              914FT6zIbfk/fEzZVlO2y6LDoOs5oVfCwAILydlr9tOrnvzPOXoQBGF9hP3EHyOm
              bHEYuB3uCsxXvTzyWErnXfV7r+rmxLY1rR6xdnWm5hi4ePEDpeAp8O6bYyWdnh5s
              v6vb/rncxWu117A2A6kWn8QsICpp53Wi3HLPwgU49Y2RoBMz80t4SDBOZIjdoPCF
              p4kSBx2JquB32coLGi3ahbNlzlTC3rRl4O6pfq7doivCnas1gFwqC18zdH5bqy3S
              ZhQqr+o/yyEWDaqgvn52P8VWrI7IewoMgnFkAW9pXT2NmJ9LFYfBi6J93sBoQ66z
              qPzIUAECgYEA3Xbbc5jXgAh2KLBhbXAcgo8lwfJ/l5U/63Hdtag1MoXxqGbvoYVT
              A0taW/WOy65maoiVWNkgkh8JXZx0jlw4i091ANYvddAXPbSvxAcuxYCUhnmyOTcY
              aIXYSND7R3oAMI20ZaoN3wSky1zMI/Mawq4kwCuNjSoiavgKfANHPqUCgYEAzzYj
              6b1nVTz1H9Q+oIOhOO1yx5yZsnkjigL+GwKij9nH54gtkQ2PqfsKFXIZ5WFUpGn9
              XZxGxpNpuP0JaH0xvZIvB80QBSTk46MfgUtapVMXutYpTLNyZayT3hBr6oasNZFw
              oSVpq3NUhgfJHoaZrlHbTHehq9zMBESsnjymJ2kCgYAs7v2toZgvyQe4T7kkzDds
              ogCmLj6HEegrLCowvlU00AptAZ2jJvrl0zcdK2ByoQr0mIu8wCkknJl43dKkQ7/R
              PCjgJ5TvkW31viBfZJmvxtvbwPtRMoWIR4fPll81bGJ3d3jfm7Y+xqFtBYIB1URb
              tZuNRgjtWFwtWfA+oyekZQKBgAXGyZuDhzTuHRtFDHXnFYCDxhZgfDxoeiAn0zOn
              kCaYeKUwu6x2h1HCyNYuNyCY5QYsWj7Y03RHucPJchCypMdXIu6BvfeWvrbF3mP5
              WM6REXFI9R/JROAmvnyLUqbYGEbqBgzIATkhXvLZlra+I9yjNYzdLOmgnyNjUria
              kjs5AoGBAJX8tiF2NrbKSPJHHlTNibkeZfP2mda6YnxpfVS92stQd8Cqd/Gm2MFd
              nl/bnSQpKWkBe3Pg2Gc1VNMY9VhNhqhQ4f9KH6DBoMI0GxGMsjxNeKLkxjT9tZCp
              lx85nJ90ZBxyVaFZ6hJOshnRqrwxCAggxR4+NsamKZuT2Vobc98H
              -----END RSA PRIVATE KEY-----
            passphrase:
            certificate: |
              -----BEGIN CERTIFICATE-----
              MIIDBDCCAewCCQCxOWmtMqp3vzANBgkqhkiG9w0BAQsFADBDMQswCQYDVQQGEwJD
              TjELMAkGA1UECAwCR0QxCzAJBgNVBAcMAkdaMQwwCgYDVQQKDANHUkcxDDAKBgNV
              BAMMA0dSRzAgFw0yMjA3MTkwNjQxNTVaGA8yMTIyMDYyNTA2NDE1NVowQzELMAkG
              A1UEBhMCQ04xCzAJBgNVBAgMAkdEMQswCQYDVQQHDAJHWjEMMAoGA1UECgwDR1JH
              MQwwCgYDVQQDDANHUkcwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCz
              QfGWOAEsq0IZNSgJf8XKPME2oHdoavib/TWVp8wcJ+hdd4zHsweeFartWOCzdL+3
              xSX7QOAj47zqmm+Ytcdvx0OCBOOixwWH8jJyAg3+sRae775D9SHgkD7Nf2yju+lj
              k0sJsYMxTSoWZVfCVM1juHA0acgGh8y1l/X/Wko3yKeAmp7MdY0vGIj/Ji/NCIvH
              EzdhRHrXjujpaaEl/h8wO0G/1/VhQbxLBa4ADOMUtu1yoUnLZYZRAzNWXxM+n0xH
              7nZ3gbZodxS9iyU0iKxHi4bjWbgC+DxMhMagfUfvC+y2S1fgo+Yjb+9K4RAmq46m
              csZTzKeD1qJnihR9wdStAgMBAAEwDQYJKoZIhvcNAQELBQADggEBADZYE3h4F7XB
              cGPALRw4iQPrEU7hprkijZ/Xdhj1UtBajR4qxMFdu6e4f6FotdP0T8upXqnJm0O3
              5IzNIvIbat2Z+6de6BcwSbhRSfXj11V00ZMupcpGy8Vyk2LAjde9f596KT4TP5fM
              Wm2S4vleLTHZHxpGUwVykNhbVSUvCfypn7ItmfYfIpTwD3Hijy1QmSi8dC8+Utes
              MlrUA+uAOdk0rumXaiDw8it6VPMGhdSaOnAxj1iCZdDtJBmVn9qR45PpgOol3HuL
              BKIG/OlF9Ls/iS7RQgFizNpeJkTNrTG6or7V9nM2DCKUy8Md4R5t6EK/4KzLbx9j
              i8LVdTB8Lgc=
              -----END CERTIFICATE-----
        providers:
          - alias: test-sp
            metadata: http://localhost:8082/saml-sp/saml2/service-provider-metadata/test-sp
            linktext: test-sp
